spring:
  datasource:
      url: ${APP_MYSQL_DATASOURCE_URL:jdbc:mysql://localhost:3306/mydb}
      username: ${APP_MYSQL_USERNAME:user}
      password: ${APP_MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

